# Change these first
owner: wardbeyens # Your GitHub organization or username, where this repository lives
repo: monitor # The name of this repository

sites:
  - name: Wardbeyens
    url: https://wardbeyens.be
  - name: Wabyte
    url: https://wabyte.com
  - name: Grafi
    url: https://grafi.ml
  - name: Requests
    url: https://requests.grafi.ml/
  - name: Wardflix
    url: https://wardflix.ga/
  - name: Code server
    url: https://code.wabyte.com/
  - name: Trainconnections
    url: https://trainconnections.slowby.ga/
  - name: Trainconnections API
    url: https://api.trainconnections.slowby.ga/health
  - name: Slowby.travel
    url: https://www.slowby.travel/
    

status-website:
  # cname: demo.upptime.js.org
  baseUrl: /monitor
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Ward's Uptime Monitor
  #introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  #introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
